version: "3.8"

services:
  dev:
    container_name: nomera_api_dev
    image: nomera-api-dev:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:dev
    ports:
      - 8080:8080
      - 9229:9229
    networks:
      - nomera-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
  prod:
    container_name: nomera_api_prod
    image: nomera-api-prod:1.0.0
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    command: npm run start:prod
    ports:
      - 8080:8080
      - 9229:9229
    networks:
      - nomera-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

networks:
  nomera-network:
