# fly.toml file generated for nomera-dev on 2022-03-04T13:50:34+08:00

app = "nomera-dev"


[env]
  PORT=8080
  ADMIN_EMAIL = "allan.alzula@gmail.com.com"
  ADMIN_MOBILE_NUMBER = "09064317892"
  ADMIN_PASSWORD = "Password@123"
  ADMIN_USERNAME = "adminallan"
  CACHE_TTL = 5
  COOKIE_SECRET = "2NBRFDdq25jDjy8NNWkW2PLWTJFuXY32"
  CRYPTO_ENCRYPTION_KEY = "UeSmWoserKCQRtWb9koKMW2b5TriuxdJ"
  DB_DATABASE = "microservice_nomera"
  DB_HOST = "nomera-database-dev.clbeuw3gib27.ap-southeast-1.rds.amazonaws.com"
  DB_PASS = "4IEpRUDTOyUimmPPuGE4"
  DB_PORT = 3306
  DB_TYPE = "mysql"
  DB_USER = "admin"
  JWT_EXPIRES = 172800
  JWT_SECRET = "K23YTgon8QhcF8WRh6CbTDGia55RxMvN"
  NODE_ENV = "development"
  REFRESH_TOKEN_SECRET = "BMGrmHa6i4ahvSvS55NERMzJfqBbCUjr"
  SWAGGER_HIDE_MODELS = true
  SWAGGER_PASSWORD = 123456
  SWAGGER_USERNAME = "nomera"

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 6
    timeout = "2s"
